/* Generated By:JavaCC: Do not edit this line. ComplexNumbersCalculatorTreeConstants.java Version 5.0 */
package complexNumbersCalculator;

public interface ComplexNumbersCalculatorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSEMICOLON = 1;
  public int JJTEND = 2;
  public int JJTEXPRESSION = 3;
  public int JJTPLUS = 4;
  public int JJTMINUS = 5;
  public int JJTTERM = 6;
  public int JJTMULTIPLY = 7;
  public int JJTDIVIDE = 8;
  public int JJTPRIMARY = 9;
  public int JJTPREVIOUS = 10;
  public int JJTOPEN_PAR = 11;
  public int JJTCLOSE_PAR = 12;
  public int JJTCOMPLEX_NUMBER = 13;
  public int JJTCOSINUS = 14;
  public int JJTSINUS = 15;
  public int JJTE = 16;
  public int JJTREAL_PART = 17;
  public int JJTIMAGINARY_PART = 18;
  public int JJTCONJUGATE = 19;


  public String[] jjtNodeName = {
    "start",
    "semicolon",
    "end",
    "expression",
    "plus",
    "minus",
    "term",
    "multiply",
    "divide",
    "primary",
    "previous",
    "open_par",
    "close_par",
    "complex_number",
    "cosinus",
    "sinus",
    "e",
    "real_part",
    "imaginary_part",
    "conjugate",
  };
}
/* JavaCC - OriginalChecksum=076f9dc849739c1d4c26f7dbcc45f100 (do not edit this line) */
