/* Generated By:JavaCC: Do not edit this line. ComplexNumbersCalculatorVisitor.java Version 5.0 */
package complexNumbersCalculator;

public interface ComplexNumbersCalculatorVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=c67ec3caf8de922aee23c5656a6704e6 (do not edit this line) */
