/* Generated By:JJTree&JavaCC: Do not edit this line. ComplexNumbersCalculatorConstants.java */
package complexNumbersCalculator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComplexNumbersCalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int OPEN_PAR = 10;
  /** RegularExpression Id. */
  int CLOSE_PAR = 11;
  /** RegularExpression Id. */
  int PREVIOUS = 12;
  /** RegularExpression Id. */
  int COMPLEX_NUMBER = 13;
  /** RegularExpression Id. */
  int REAL_PART = 14;
  /** RegularExpression Id. */
  int IMAGINARY_PART = 15;
  /** RegularExpression Id. */
  int CONJUGATE = 16;
  /** RegularExpression Id. */
  int SINUS = 17;
  /** RegularExpression Id. */
  int COSINUS = 18;
  /** RegularExpression Id. */
  int E = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "<COMPLEX_NUMBER>",
    "\"re\"",
    "\"im\"",
    "\"con\"",
    "<SINUS>",
    "<COSINUS>",
    "<E>",
    "\";\"",
    "\"end\"",
  };

}
